version: "3.8"
services:
  activity:
    expose:
      - 3000
    environment:
      PRODUCTION: "true"
  auth:
    expose:
      - 3000
    environment:
      PRODUCTION: "true"
  expense:
    expose:
      - 3000
    environment:
      PRODUCTION: "true"
  group:
    expose:
      - 3000
    environment: 
      PRODUCTION: "true"
  notification:
    expose:
      - 3000
    environment:
      PRODUCTION: "true"
  user:
    expose:
      - 3000
    environment:
      PRODUCTION: "true"
  api-docs:
    expose:
      - 3000
    environment:
      PRODUCTION: "true"  
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - activity
      - auth
      - expense
      - group
      - notification
      - user
      - api-docs
    ports:
      - 80:80
    environment:
      PRODUCTION: "true"
