version: "3.8"
services:
  nats-streaming:
    image: nats-streaming:0.17.0
  auth-cache:
    image: redis
  auth-db:
    image: mongo
  user-db:
    image: mongo
  expense-db:
    image: neo4j
  auth:
    image: chortech/auth:latest
    depends_on:
      - auth-db
      - auth-cache
  user:
    image: chortech/user:latest
    depends_on:
      - user-db
  expense:
    image: chortech/expense:latest
    depends_on:
      - expense-db
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - auth
      - expense
      - user