version: "3.8"
services:
  nats-streaming:
    image: nats-streaming:0.17.0
    container_name: nats-streaming
    command:
      [
        "-p",
        "4222",
        "-m",
        "8222",
        "-hbi",
        "5s",
        "-hbt",
        "5s",
        "-hbf",
        "2",
        "-SD",
        "-cid",
        "chortec",
      ]
    expose:
      - 4222
      - 8222
    ports:
      - 4222:4222
      - 8222:8222
    logging:
      driver: none
  auth-cache:
    image: redis
    container_name: auth-cache-redis
    expose:
      - 6379
    logging:
      driver: none
  auth-db:
    image: mongo
    container_name: auth-db-mongo
    expose:
      - 27017
    logging:
      driver: none
  user-db:
    image: mongo
    container_name: user-db-mongo
    expose:
      - 27017
    logging:
      driver: none
  group-db:
    image: mongo
    container_name: group-db-mongo
    expose:
      - 27017
    logging:
      driver: none
  expense-db:
    image: neo4j
    container_name: expense-db-neo4j
    volumes:
      - ./expense/plugins:/plugins
      - ./expense/conf:/conf
    environment:
      NEO4J_AUTH: none
    expose:
      - 7687
      - 7474
    ports:
      - 7687:7687
      - 7474:7474
    logging:
      driver: none
  activity-db:
    image: mongo
    container_name: activity-db-mongo
    expose:
      - 27017
    logging:
      driver: none
  auth:
    image: chortech/auth:latest
    container_name: auth-service
    restart: always
    expose:
      - 3000
    depends_on:
      - auth-cache
      - auth-db
    environment:
      STAGE: "true"
      HOST: http://5.253.25.167/
      REDIS_URL: redis://auth-cache:6379
      MONGO_URL: mongodb://auth-db:27017
      NATS_URL: http://nats-streaming:4222
      NATS_CLUSTER_ID: chortec
      SECRETS: /run/secrets/auth-service-secrets
      DEBUG: "true"
    secrets:
      - auth-service-secrets
  user:
    image: chortech/user:latest
    container_name: user-service
    restart: always
    expose:
      - 3000
    depends_on:
      - user-db
    environment:
      HOST: http://5.253.25.167/
      MONGO_URL: mongodb://user-db:27017
      NATS_URL: http://nats-streaming:4222
      NATS_CLUSTER_ID: chortec
      SECRETS: /run/secrets/user-service-secrets
      DEBUG: "true"
    secrets:
      - user-service-secrets
  group:
    image: chortech/group:latest
    container_name: group-service
    restart: always
    expose:
      - 3000
    depends_on:
      - group-db
    environment:
      HOST: http://5.253.25.167/
      MONGO_URI: mongodb://group-db:27017
      NATS_URL: http://nats-streaming:4222
      NATS_CLUSTER_ID: chortec
      SECRETS: /run/secrets/group-service-secrets
      DEBUG: "true"
    secrets:
      - group-service-secrets
  expense:
    image: chortech/expense:latest
    container_name: expense-service
    restart: always
    environment:
      HOST: http://5.253.25.167/
      NEO4J_URL: bolt://expense-db:7687
      NATS_URL: http://nats-streaming:4222
      NATS_CLUSTER_ID: chortec
      DEBUG: "true"
    expose:
      - 3000
    depends_on:
      - expense-db
      - nats-streaming
  activity:
    image: chortech/activity:latest
    container_name: activity-service
    restart: always
    expose:
      - 3000
    depends_on:
      - group-db
    environment:
      HOST: http://5.253.25.167/
      MONGO_URI: mongodb://activity-db:27017
      NATS_URL: http://nats-streaming:4222
      NATS_CLUSTER_ID: chortec
      DEBUG: "true"
  api-docs:
    image: chortech/api-docs
    container_name: api-docs
    restart: always
    expose:
      - 3000
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - auth
      - expense
      - user
      - api-docs
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: none
secrets:
  user-service-secrets:
    file: ./secrets/user-service-secrets.json
  auth-service-secrets:
    file: ./secrets/auth-service-secrets.json
  group-service-secrets:
    file: ./secrets/group-service-secrets.json
