apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: chortech/user
          env:
            - name: MONGO_URL
              value: 'mongodb://user-mongo-srv:27017'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: chortec
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef: 
                  fieldPath: metadata.name
            - name: STORAGE_REGION
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: STORAGE_REGION
            - name: STORAGE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: STORAGE_ENDPOINT
            - name: STORAGE_ACCESSKEYID
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: STORAGE_ACCESSKEYID
            - name: STORAGE_SECRET
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: STORAGE_SECRET
            - name: STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: storage-secret
                  key: STORAGE_BUCKET
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000