name: tests-activity

on:
  pull_request:
    paths:
      - 'activity/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd activity && npm install && npm run test:ci
